export const mockTasks = [
  {
    id: '1',
    title: 'Title 1',
    priority: 'urgent',
    priorityIndex: 1,
    description: '',
  },
  {
    id: '2',
    title: 'Title 2',
    priority: 'low',
    priorityIndex: 2,
    description: '',
  },
  {
    id: '3',
    title: 'Title 3',
    priority: 'high',
    priorityIndex: 3,
    description: '',
  },
  {
    id: '4',
    title: 'Title 4',
    priority: 'medium',
    priorityIndex: 4,
    description: '',
  },
  {
    id: '5',
    title: 'Title 5',
    priority: 'high',
    priorityIndex: 5,
    description: '',
  },
  {
    id: '6',
    title: 'Title 6',
    priority: 'low',
    priorityIndex: 6,
    description: '',
  },
  {
    id: '7',
    title: 'Title 7',
    priority: 'low',
    priorityIndex: 7,
    description: '',
  },
  {
    id: '8',
    title: 'Title 8',
    priority: 'low',
    priorityIndex: 8,
    description: '',
  },
  {
    id: '9',
    title: 'Title 9',
    priority: 'urgent',
    priorityIndex: 9,
    description: '',
  },
  {
    id: '10',
    title: 'Title 10',
    priority: 'medium',
    priorityIndex: 10,
    description: '',
  },
];
